export type Lang = "en" | "es";

export const copy = {
  en: {
    nav: {
      agenda: "Agenda",
      gallery: "Gallery",
      video: "Video",
      notes: "Notes",
      booking: "Booking",
      epk: "EPK",
    },
    epk: {
      corners: ["DJ", "Open format", "Ibiza"],
      cover: {
        kicker: "Press kit",
        season: "Summer 26",
        roles: "DJ · Open format · Ibiza",
        tagline: "An experience beyond music",
      },
      about: {
        title: "About",
        p: [
          "Born in San Miguel de Tucumán, Argentina. Based in Ibiza.",
          "Open-format sets across Urban, Latin House and House — slow warm-ups, emotional openings, peak-times built with patience.",
          "Six years. Sixty nights a year. Four countries.",
        ],
      },
      statement: "I don't want the night to be loud. I want it to be inevitable.",
      rooms: {
        label: "Rooms",
        note: "Ushuaïa — The Unexpected",
        p: "From Ushuaïa's The Unexpected to Lío, Cova Santa, and the rooftops and beach houses of the Riviera Maya.",
      },
      rider: {
        title: "Technical rider",
        lines: ["Urban · Latin House · House — open format", "Full technical rider on request"],
      },
      contactLabel: "Bookings & press",
      print: "Print / Save as PDF",
    },
    hero: {
      tagline: "An experience beyond music",
      location: "Ibiza · Worldwide",
      cta: "Bookings",
      listen: "Listen",
    },
    home: {
      side: { rooms: "Rooms", archive: "Archive", interview: "Interview", listen: "Listen", booking: "Booking" },
      hero: {
        presents: "Ibiza · presents",
        tagline: "An experience beyond music",
        genres: ["Open format", "Urban", "Latin house"],
        ctaBook: "Check a date",
        ctaListen: "Hear a set",
        coords: "38.98°N 1.43°E",
        season: "Summer 26",
      },
      rails: {
        label: "Rooms & cities",
        note: "Ushuaïa — The Unexpected",
        statLeft: "Six years · sixty nights a year · four countries",
        statRight: "Open format · Ibiza based",
      },
      quote: {
        text: "Nobody remembers the tracklist. Everybody remembers the feeling.",
        route: "Tucumán → Ibiza → wherever the night is",
      },
      tabs: { archive: "Archive", interview: "Interview", listen: "Listen", booking: "Booking" },
      archive: { count: "frames in the archive", seeAll: "See all" },
      interview: {
        label: "The interview",
        date: "Recorded in Ibiza, June",
        caption: "1/4s, handheld",
        quote: "“I don't want the night to be loud. I want it to be inevitable.”",
        qa: [
          {
            q: "On the first hour",
            a: "Everyone wants the drop. The first hour is where you earn it — you're deciding what kind of room it's going to be. I play slower than people expect and I never apologise for it.",
          },
          {
            q: "On coming from Tucumán",
            a: "Nobody there is waiting for a DJ from Argentina. You learn to be undeniable before you're known. That's still how I read a booking — the room owes me nothing.",
          },
          {
            q: "On open format",
            a: "Urban, latin house, house — I'm not defending a genre, I'm holding a mood. The edits are mine so the transitions can be things nobody has heard.",
          },
        ],
        more: "Full interview in the press kit →",
        facts: [
          ["Sound", "Urban · Latin House · House — open format"],
          ["Base", "Ibiza · worldwide"],
          ["Adjacent to", "Peggy Gou · CamelPhat · Michael Bibi · Maceo Plex"],
          ["Rider", "Technical rider on request"],
        ],
      },
      listen: {
        title: "Recorded nights",
        play: "Play",
        tracks: [
          { t: "Live set — full session", d: "1h 58m" },
          { t: "Rooftop, golden hour", d: "62m" },
          { t: "Peak time, dark room", d: "48m" },
        ],
        reels: "Reels",
      },
      booking: {
        title: "Check\na date",
        lead: "Clubs, festivals, premium and private events, worldwide. Answers within 48 hours.",
        bookings: "Bookings",
        press: "Press kit",
        pressLink: "Download PDF",
        rider: "Rider",
        riderVal: "On request",
        form: {
          name: "Name",
          email: "Email",
          venue: "Venue / city",
          date: "Date / slot",
          msg: "What the night is",
          send: "Send request",
          sent: "Sent — thank you",
        },
      },
    },
    agenda: {
      title: "Agenda",
      empty: "New dates are being confirmed.",
      emptySub: "Want Maru in your city or venue?",
      request: "Request availability",
      tickets: "Tickets",
    },
    gallery: {
      title: "Gallery",
    },
    video: {
      title: "Video",
      channel: "YouTube channel",
      loopsTitle: "Moments",
      setsTitle: "Full sets",
    },
    booking: {
      title: "Booking",
      lead: "For bookings, press and collaborations:",
      formName: "Name",
      formEmail: "Email",
      formDate: "Date / city / venue",
      formMessage: "Tell us about the event",
      send: "Send request",
      rider: "Technical rider available upon request.",
      follow: "Follow",
    },
    notes: {
      title: "Notes",
      empty: "Notes from the booth — stories, music and moments. Coming soon.",
      newsletterLabel: "The list",
      newsletter: "Be the first to know about new dates and music.",
      subscribe: "Join the list",
    },
    footer: {
      rights: "All rights reserved",
      bookings: "Bookings",
    },
  },
  es: {
    nav: {
      agenda: "Agenda",
      gallery: "Galería",
      video: "Video",
      notes: "Notas",
      booking: "Booking",
      epk: "EPK",
    },
    epk: {
      corners: ["DJ", "Open format", "Ibiza"],
      cover: {
        kicker: "Press kit",
        season: "Verano 26",
        roles: "DJ · Open format · Ibiza",
        tagline: "Una experiencia más allá de la música",
      },
      about: {
        title: "About",
        p: [
          "Nacida en San Miguel de Tucumán, Argentina. Radicada en Ibiza.",
          "Sets open format entre Urban, Latin House y House — warm-ups lentos, openings emocionales, peak-times construidos con paciencia.",
          "Seis años. Sesenta noches al año. Cuatro países.",
        ],
      },
      statement: "No quiero que la noche sea fuerte. Quiero que sea inevitable.",
      rooms: {
        label: "Salas",
        note: "Ushuaïa — The Unexpected",
        p: "Desde The Unexpected de Ushuaïa hasta Lío, Cova Santa y los rooftops y beach houses de la Riviera Maya.",
      },
      rider: {
        title: "Rider técnico",
        lines: ["Urban · Latin House · House — open format", "Rider técnico completo bajo petición"],
      },
      contactLabel: "Bookings & prensa",
      print: "Imprimir / Guardar PDF",
    },
    hero: {
      tagline: "Una experiencia más allá de la música",
      location: "Ibiza · Worldwide",
      cta: "Bookings",
      listen: "Escuchar",
    },
    home: {
      side: { rooms: "Salas", archive: "Archivo", interview: "Entrevista", listen: "Escuchar", booking: "Booking" },
      hero: {
        presents: "Ibiza · presenta",
        tagline: "Una experiencia más allá de la música",
        genres: ["Open format", "Urban", "Latin house"],
        ctaBook: "Consultar una fecha",
        ctaListen: "Escuchar un set",
        coords: "38.98°N 1.43°E",
        season: "Verano 26",
      },
      rails: {
        label: "Salas y ciudades",
        note: "Ushuaïa — The Unexpected",
        statLeft: "Seis años · sesenta noches al año · cuatro países",
        statRight: "Open format · base en Ibiza",
      },
      quote: {
        text: "Nadie recuerda el tracklist. Todos recuerdan la sensación.",
        route: "Tucumán → Ibiza → donde esté la noche",
      },
      tabs: { archive: "Archivo", interview: "Entrevista", listen: "Escuchar", booking: "Booking" },
      archive: { count: "frames en el archivo", seeAll: "Ver todo" },
      interview: {
        label: "La entrevista",
        date: "Grabada en Ibiza, junio",
        caption: "1/4s, a mano",
        quote: "“No quiero que la noche sea fuerte. Quiero que sea inevitable.”",
        qa: [
          {
            q: "Sobre la primera hora",
            a: "Todos quieren el drop. La primera hora es donde te lo ganás: ahí decidís qué tipo de sala va a ser. Toco más lento de lo que la gente espera y nunca me disculpo por eso.",
          },
          {
            q: "Sobre venir de Tucumán",
            a: "Allá nadie está esperando a una DJ de Argentina. Aprendés a ser innegable antes de ser conocida. Así sigo leyendo un booking: la sala no me debe nada.",
          },
          {
            q: "Sobre el open format",
            a: "Urban, latin house, house — no defiendo un género, sostengo un clima. Los edits son míos para que las transiciones sean cosas que nadie escuchó.",
          },
        ],
        more: "Entrevista completa en el press kit →",
        facts: [
          ["Sonido", "Urban · Latin House · House — open format"],
          ["Base", "Ibiza · worldwide"],
          ["Cercana a", "Peggy Gou · CamelPhat · Michael Bibi · Maceo Plex"],
          ["Rider", "Rider técnico bajo petición"],
        ],
      },
      listen: {
        title: "Noches grabadas",
        play: "Play",
        tracks: [
          { t: "Set en vivo — sesión completa", d: "1h 58m" },
          { t: "Rooftop, golden hour", d: "62m" },
          { t: "Peak time, cuarto oscuro", d: "48m" },
        ],
        reels: "Reels",
      },
      booking: {
        title: "Consultar\nuna fecha",
        lead: "Clubs, festivales, eventos premium y privados, worldwide. Respuesta en 48 horas.",
        bookings: "Bookings",
        press: "Press kit",
        pressLink: "Descargar PDF",
        rider: "Rider",
        riderVal: "Bajo petición",
        form: {
          name: "Nombre",
          email: "Email",
          venue: "Venue / ciudad",
          date: "Fecha / horario",
          msg: "Qué es la noche",
          send: "Enviar solicitud",
          sent: "Enviado — gracias",
        },
      },
    },
    agenda: {
      title: "Agenda",
      empty: "Nuevas fechas en confirmación.",
      emptySub: "¿Querés a Maru en tu ciudad o venue?",
      request: "Solicitar disponibilidad",
      tickets: "Entradas",
    },
    gallery: {
      title: "Galería",
    },
    video: {
      title: "Video",
      channel: "Canal de YouTube",
      loopsTitle: "Momentos",
      setsTitle: "Sets completos",
    },
    booking: {
      title: "Booking",
      lead: "Para bookings, prensa y colaboraciones:",
      formName: "Nombre",
      formEmail: "Email",
      formDate: "Fecha / ciudad / venue",
      formMessage: "Contanos sobre el evento",
      send: "Enviar solicitud",
      rider: "Rider técnico disponible bajo petición.",
      follow: "Seguir",
    },
    notes: {
      title: "Notas",
      empty: "Notas desde la cabina — historias, música y momentos. Muy pronto.",
      newsletterLabel: "La lista",
      newsletter: "Enterate primero de nuevas fechas y música.",
      subscribe: "Unirme a la lista",
    },
    footer: {
      rights: "Todos los derechos reservados",
      bookings: "Bookings",
    },
  },
} as const;

export const influences = ["Peggy Gou", "CamelPhat", "Michael Bibi", "Maceo Plex"];
