export type Lang = "en" | "es";

export const copy = {
  en: {
    nav: {
      agenda: "Agenda",
      gallery: "Gallery",
      notes: "Notes",
      booking: "Booking",
      epk: "EPK",
    },
    epk: {
      cover: {
        kicker: "Press kit",
        loc: "Ibiza · worldwide",
        tagline: "An experience beyond music",
        role: "Open format DJ",
      },
      running: "Maru Bravo — press kit",
      contents: {
        quote: "The booking is not a DJ slot. It is the shape of your whole night.",
        items: [
          ["01", "Who she is", "p. 03"],
          ["02", "The sound", "p. 05"],
          ["03", "Rooms & cities", "p. 06"],
          ["04", "In numbers", "p. 07"],
          ["05", "Selects", "p. 09"],
          ["06", "Booking & logistics", "p. 10"],
        ],
      },
      who: {
        head: "01 — Who she is",
        lead: "DJ from San Miguel de Tucumán, based in Ibiza. Open format — urban, latin house, house.",
        body: "She learned the floor from the other side of the booth: warm-ups that take their time, peak times built like an argument, and a read of the room that does not depend on the tracklist.",
        quote: "“I don't want the night to be loud. I want it to be inevitable.”",
        facts: [
          ["Sound", "Open format"],
          ["Base", "Ibiza"],
          ["Since", "2019"],
          ["Slots", "Day · sunset · peak"],
          ["Rider", "On request"],
        ],
      },
      plateA: { quote: "The whole room turns the same direction.", caption: "Rooftop — Playa del Carmen" },
      sound: {
        head: "02 — The sound",
        title: ["Open", "format"],
        genres: ["Urban", "Latin house", "House"],
        body: "Own edits and unreleased tracks. Not a genre to defend — a mood to hold, for as long as the room is hers.",
      },
      rooms: {
        head: "03 — Rooms & cities",
        venues: [
          ["Ushuaïa", "The Unexpected · peak"],
          ["Lío", "Dinner → floor"],
          ["Cova Santa", "Open air"],
          ["Nassau Beach Club", "Day"],
          ["Playa Soleil", "Day → sunset"],
          ["Roto", "Late"],
          ["Keeper", "Club"],
          ["Dunes", "Beach"],
        ],
        citiesLabel: "Cities",
        cities: "Ibiza · Barcelona · Madrid · Alicante · Buenos Aires · Córdoba · Tucumán · Tulum · Playa del Carmen · Cancún · Monaco",
      },
      numbers: {
        head: "04 — In numbers",
        stats: [
          ["6+", "Years behind the decks"],
          ["60", "Nights a year"],
          ["11", "Cities"],
          ["4", "Countries"],
        ],
        line: "Ushuaïa · Lío · Cova Santa · Playa Soleil · Nassau Beach Club · Roto · Keeper · Dunes — and the rooftops and beach houses of the Riviera Maya.",
      },
      plateB: { title: ["Feel-good music", "for dark rooms"], left: "Peak time", right: "Ibiza" },
      selects: {
        head: "05 — Selects",
        captions: "Rooftop above the sea · Walking in · Street portrait",
        gallery: "Full gallery — marubravo.com",
      },
      booking: {
        head: "06 — Booking & logistics",
        lead: "Clubs, festivals, premium and private events, worldwide. Answers within 48 hours.",
        facts: [
          ["Sound", "Open format"],
          ["Base", "Ibiza"],
          ["Events", "Clubs · festivals · private"],
          ["Rider", "On request"],
          ["Set length", "On request"],
          ["Since", "2019"],
        ],
        site: "Site",
      },
      foot: { left: "Maru Bravo — press kit", right: "Ibiza · worldwide" },
      print: "Print / Save as PDF",
    },
    hero: {
      tagline: "An experience beyond music",
      location: "Ibiza · Worldwide",
      cta: "Bookings",
      listen: "Listen",
    },
    home: {
      side: { home: "Home", epk: "EPK", bookings: "Bookings" },
      hero: {
        presents: "Ibiza · presents",
        tagline: "An experience beyond music",
        genres: ["Open format", "Urban", "Latin house"],
        ctaBook: "Check a date",
        ctaListen: "Hear a set",
        coords: "38.98°N 1.43°E",
        season: "Summer 26",
      },
      quote: {
        text: "Nobody remembers the tracklist. Everybody remembers the feeling.",
        route: "Tucumán → Ibiza → wherever the night is",
      },
      tabs: { archive: "Archive", interview: "Interview", listen: "Listen", booking: "Booking" },
      archive: { count: "frames in the archive", seeAll: "See all" },
      interview: {
        label: "The interview",
        date: "Recorded in Ibiza, June",
        caption: "1/4s, handheld",
        quote: "“I don't want the night to be loud. I want it to be inevitable.”",
        qa: [
          {
            q: "On the first hour",
            a: "Everyone wants the drop. The first hour is where you earn it — you're deciding what kind of room it's going to be. I play slower than people expect and I never apologise for it.",
          },
          {
            q: "On coming from Tucumán",
            a: "Nobody there is waiting for a DJ from Argentina. You learn to be undeniable before you're known. That's still how I read a booking — the room owes me nothing.",
          },
          {
            q: "On open format",
            a: "Urban, latin house, house — I'm not defending a genre, I'm holding a mood. The edits are mine so the transitions can be things nobody has heard.",
          },
        ],
        more: "Full interview in the press kit →",
        facts: [
          ["Sound", "Urban · Latin House · House — open format"],
          ["Base", "Ibiza · worldwide"],
          ["Adjacent to", "Peggy Gou · CamelPhat · Michael Bibi · Maceo Plex"],
          ["Rider", "Technical rider on request"],
        ],
      },
      listen: {
        title: "Recorded nights",
        play: "Play",
        tracks: [
          { t: "Live set — full session", d: "1h 58m" },
          { t: "Rooftop, golden hour", d: "62m" },
          { t: "Peak time, dark room", d: "48m" },
        ],
        reels: "Reels",
      },
      booking: {
        title: "Check\na date",
        lead: "Clubs, festivals, premium and private events, worldwide. Answers within 48 hours.",
        bookings: "Bookings",
        press: "Press kit",
        pressLink: "Download PDF",
        rider: "Rider",
        riderVal: "On request",
        form: {
          name: "Name",
          email: "Email",
          venue: "Venue / city",
          date: "Date / slot",
          msg: "What the night is",
          send: "Send request",
          sent: "Sent — thank you",
        },
      },
    },
    agenda: {
      title: "Agenda",
      empty: "New dates are being confirmed.",
      emptySub: "Want Maru in your city or venue?",
      request: "Request availability",
      tickets: "Tickets",
    },
    gallery: {
      title: "Gallery",
      clips: "clips",
    },
    booking: {
      title: "Booking",
      lead: "For bookings, press and collaborations:",
      formName: "Name",
      formEmail: "Email",
      formDate: "Date / city / venue",
      formMessage: "Tell us about the event",
      send: "Send request",
      rider: "Technical rider available upon request.",
      follow: "Follow",
    },
    notes: {
      title: "Notes",
      empty: "Notes from the booth — stories, music and moments. Coming soon.",
      newsletterLabel: "The list",
      newsletter: "Be the first to know about new dates and music.",
      subscribe: "Join the list",
    },
    footer: {
      rights: "All rights reserved",
      bookings: "Bookings",
    },
  },
  es: {
    nav: {
      agenda: "Agenda",
      gallery: "Galería",
      notes: "Notas",
      booking: "Booking",
      epk: "EPK",
    },
    epk: {
      cover: {
        kicker: "Press kit",
        loc: "Ibiza · worldwide",
        tagline: "Una experiencia más allá de la música",
        role: "DJ open format",
      },
      running: "Maru Bravo — press kit",
      contents: {
        quote: "El booking no es un slot de DJ. Es la forma de toda tu noche.",
        items: [
          ["01", "Quién es", "p. 03"],
          ["02", "El sonido", "p. 05"],
          ["03", "Salas y ciudades", "p. 06"],
          ["04", "En números", "p. 07"],
          ["05", "Selección", "p. 09"],
          ["06", "Booking y logística", "p. 10"],
        ],
      },
      who: {
        head: "01 — Quién es",
        lead: "DJ de San Miguel de Tucumán, radicada en Ibiza. Open format — urban, latin house, house.",
        body: "Aprendió la pista desde el otro lado de la cabina: warm-ups que se toman su tiempo, peak times construidos como un argumento, y una lectura de la sala que no depende del tracklist.",
        quote: "“No quiero que la noche sea fuerte. Quiero que sea inevitable.”",
        facts: [
          ["Sonido", "Open format"],
          ["Base", "Ibiza"],
          ["Desde", "2019"],
          ["Slots", "Día · sunset · peak"],
          ["Rider", "Bajo petición"],
        ],
      },
      plateA: { quote: "La sala entera gira en la misma dirección.", caption: "Rooftop — Playa del Carmen" },
      sound: {
        head: "02 — El sonido",
        title: ["Open", "format"],
        genres: ["Urban", "Latin house", "House"],
        body: "Edits propios y tracks unreleased. No es un género que defender — es un clima que sostener, mientras la sala sea suya.",
      },
      rooms: {
        head: "03 — Salas y ciudades",
        venues: [
          ["Ushuaïa", "The Unexpected · peak"],
          ["Lío", "Cena → pista"],
          ["Cova Santa", "Open air"],
          ["Nassau Beach Club", "Día"],
          ["Playa Soleil", "Día → sunset"],
          ["Roto", "Late"],
          ["Keeper", "Club"],
          ["Dunes", "Playa"],
        ],
        citiesLabel: "Ciudades",
        cities: "Ibiza · Barcelona · Madrid · Alicante · Buenos Aires · Córdoba · Tucumán · Tulum · Playa del Carmen · Cancún · Mónaco",
      },
      numbers: {
        head: "04 — En números",
        stats: [
          ["6+", "Años en cabina"],
          ["60", "Noches al año"],
          ["11", "Ciudades"],
          ["4", "Países"],
        ],
        line: "Ushuaïa · Lío · Cova Santa · Playa Soleil · Nassau Beach Club · Roto · Keeper · Dunes — y los rooftops y beach houses de la Riviera Maya.",
      },
      plateB: { title: ["Música para sentirse bien", "en cuartos oscuros"], left: "Peak time", right: "Ibiza" },
      selects: {
        head: "05 — Selección",
        captions: "Rooftop sobre el mar · Entrando · Retrato en la calle",
        gallery: "Galería completa — marubravo.com",
      },
      booking: {
        head: "06 — Booking y logística",
        lead: "Clubs, festivales, eventos premium y privados, worldwide. Respuesta en 48 horas.",
        facts: [
          ["Sonido", "Open format"],
          ["Base", "Ibiza"],
          ["Eventos", "Clubs · festivales · privados"],
          ["Rider", "Bajo petición"],
          ["Duración", "Bajo petición"],
          ["Desde", "2019"],
        ],
        site: "Sitio",
      },
      foot: { left: "Maru Bravo — press kit", right: "Ibiza · worldwide" },
      print: "Imprimir / Guardar PDF",
    },
    hero: {
      tagline: "Una experiencia más allá de la música",
      location: "Ibiza · Worldwide",
      cta: "Bookings",
      listen: "Escuchar",
    },
    home: {
      side: { home: "Inicio", epk: "EPK", bookings: "Bookings" },
      hero: {
        presents: "Ibiza · presenta",
        tagline: "Una experiencia más allá de la música",
        genres: ["Open format", "Urban", "Latin house"],
        ctaBook: "Consultar una fecha",
        ctaListen: "Escuchar un set",
        coords: "38.98°N 1.43°E",
        season: "Verano 26",
      },
      quote: {
        text: "Nadie recuerda el tracklist. Todos recuerdan la sensación.",
        route: "Tucumán → Ibiza → donde esté la noche",
      },
      tabs: { archive: "Archivo", interview: "Entrevista", listen: "Escuchar", booking: "Booking" },
      archive: { count: "frames en el archivo", seeAll: "Ver todo" },
      interview: {
        label: "La entrevista",
        date: "Grabada en Ibiza, junio",
        caption: "1/4s, a mano",
        quote: "“No quiero que la noche sea fuerte. Quiero que sea inevitable.”",
        qa: [
          {
            q: "Sobre la primera hora",
            a: "Todos quieren el drop. La primera hora es donde te lo ganás: ahí decidís qué tipo de sala va a ser. Toco más lento de lo que la gente espera y nunca me disculpo por eso.",
          },
          {
            q: "Sobre venir de Tucumán",
            a: "Allá nadie está esperando a una DJ de Argentina. Aprendés a ser innegable antes de ser conocida. Así sigo leyendo un booking: la sala no me debe nada.",
          },
          {
            q: "Sobre el open format",
            a: "Urban, latin house, house — no defiendo un género, sostengo un clima. Los edits son míos para que las transiciones sean cosas que nadie escuchó.",
          },
        ],
        more: "Entrevista completa en el press kit →",
        facts: [
          ["Sonido", "Urban · Latin House · House — open format"],
          ["Base", "Ibiza · worldwide"],
          ["Cercana a", "Peggy Gou · CamelPhat · Michael Bibi · Maceo Plex"],
          ["Rider", "Rider técnico bajo petición"],
        ],
      },
      listen: {
        title: "Noches grabadas",
        play: "Play",
        tracks: [
          { t: "Set en vivo — sesión completa", d: "1h 58m" },
          { t: "Rooftop, golden hour", d: "62m" },
          { t: "Peak time, cuarto oscuro", d: "48m" },
        ],
        reels: "Reels",
      },
      booking: {
        title: "Consultar\nuna fecha",
        lead: "Clubs, festivales, eventos premium y privados, worldwide. Respuesta en 48 horas.",
        bookings: "Bookings",
        press: "Press kit",
        pressLink: "Descargar PDF",
        rider: "Rider",
        riderVal: "Bajo petición",
        form: {
          name: "Nombre",
          email: "Email",
          venue: "Venue / ciudad",
          date: "Fecha / horario",
          msg: "Qué es la noche",
          send: "Enviar solicitud",
          sent: "Enviado — gracias",
        },
      },
    },
    agenda: {
      title: "Agenda",
      empty: "Nuevas fechas en confirmación.",
      emptySub: "¿Querés a Maru en tu ciudad o venue?",
      request: "Solicitar disponibilidad",
      tickets: "Entradas",
    },
    gallery: {
      title: "Galería",
      clips: "clips",
    },
    booking: {
      title: "Booking",
      lead: "Para bookings, prensa y colaboraciones:",
      formName: "Nombre",
      formEmail: "Email",
      formDate: "Fecha / ciudad / venue",
      formMessage: "Contanos sobre el evento",
      send: "Enviar solicitud",
      rider: "Rider técnico disponible bajo petición.",
      follow: "Seguir",
    },
    notes: {
      title: "Notas",
      empty: "Notas desde la cabina — historias, música y momentos. Muy pronto.",
      newsletterLabel: "La lista",
      newsletter: "Enterate primero de nuevas fechas y música.",
      subscribe: "Unirme a la lista",
    },
    footer: {
      rights: "Todos los derechos reservados",
      bookings: "Bookings",
    },
  },
} as const;

export const influences = ["Peggy Gou", "CamelPhat", "Michael Bibi", "Maceo Plex"];
